# Generated by Django 5.2.8 on 2025-12-01 13:41

import authentication.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='사용자명')),
                ('role', models.CharField(choices=[('guest', '비회원'), ('user', '일반회원'), ('seller', '판매자'), ('admin', '관리자')], default='guest', max_length=20, verbose_name='역할')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='탈퇴 일시')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'users',
            },
            managers=[
                ('objects', authentication.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuthEmailCredential',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='email_credential', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('password_hash', models.CharField(max_length=128, verbose_name='비밀번호 해시')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='이메일 인증 완료')),
                ('fail_count', models.IntegerField(default=0, verbose_name='로그인 실패 횟수')),
                ('last_changed_at', models.DateTimeField(auto_now=True, verbose_name='비밀번호 변경일시')),
            ],
            options={
                'verbose_name': '이메일 인증 정보',
                'verbose_name_plural': '이메일 인증 정보',
                'db_table': 'auth_email_credentials',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('profile_image_url', models.TextField(blank=True, null=True, verbose_name='프로필 이미지 URL')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='전화번호')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('gender', models.CharField(blank=True, choices=[('male', '남성'), ('female', '여성'), ('other', '기타'), ('prefer_not_to_say', '선택 안함')], max_length=20, null=True, verbose_name='성별')),
                ('timezone', models.CharField(default='Asia/Seoul', max_length=64, verbose_name='타임존')),
                ('language', models.CharField(default='ko', max_length=10, verbose_name='선호 언어')),
                ('notification_enabled', models.BooleanField(default=True, verbose_name='알림 수신 여부')),
                ('marketing_agreed', models.BooleanField(default=False, verbose_name='마케팅 수신 동의')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='AuthGoogleAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_user_id', models.CharField(max_length=255, unique=True, verbose_name='Google 사용자 ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Google 이메일')),
                ('connected_at', models.DateTimeField(auto_now_add=True, verbose_name='연결일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_accounts', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'Google 계정',
                'verbose_name_plural': 'Google 계정',
                'db_table': 'auth_google_accounts',
            },
        ),
        migrations.CreateModel(
            name='AuthKakaoAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kakao_user_id', models.CharField(max_length=255, unique=True, verbose_name='Kakao 사용자 ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Kakao 이메일')),
                ('connected_at', models.DateTimeField(auto_now_add=True, verbose_name='연결일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kakao_accounts', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'Kakao 계정',
                'verbose_name_plural': 'Kakao 계정',
                'db_table': 'auth_kakao_accounts',
            },
        ),
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('username', models.CharField(max_length=150, verbose_name='사용자명')),
                ('password_hash', models.CharField(max_length=128, verbose_name='비밀번호 해시')),
                ('verification_code', models.CharField(max_length=64, verbose_name='인증 코드')),
                ('expires_at', models.DateTimeField(verbose_name='만료 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '가입 대기',
                'verbose_name_plural': '가입 대기',
                'db_table': 'pending_registrations',
                'indexes': [models.Index(fields=['expires_at'], name='ix_pending_reg_expires')],
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(max_length=100, verbose_name='배송지명')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='수령인 이름')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='수령인 전화번호')),
                ('postal_code', models.CharField(max_length=10, verbose_name='우편번호')),
                ('address_line1', models.CharField(max_length=255, verbose_name='기본 주소')),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='상세 주소')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본 배송지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '배송지',
                'verbose_name_plural': '배송지',
                'db_table': 'user_addresses',
            },
        ),
        migrations.CreateModel(
            name='UserPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('credit_card', '신용카드'), ('debit_card', '체크카드'), ('bank_account', '계좌이체'), ('virtual_account', '가상계좌'), ('mobile', '간편결제')], max_length=20, verbose_name='결제 수단 유형')),
                ('provider', models.CharField(max_length=50, verbose_name='결제 제공자')),
                ('card_number_last4', models.CharField(blank=True, max_length=4, null=True, verbose_name='카드 번호 마지막 4자리')),
                ('card_issuer', models.CharField(blank=True, max_length=50, null=True, verbose_name='카드 발급사')),
                ('card_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='카드 종류')),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='은행명')),
                ('account_number_last4', models.CharField(blank=True, max_length=4, null=True, verbose_name='계좌번호 마지막 4자리')),
                ('payment_gateway_token', models.TextField(blank=True, null=True, verbose_name='PG사 빌링키')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본 결제 수단')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '결제 수단',
                'verbose_name_plural': '결제 수단',
                'db_table': 'user_payment_methods',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='ix_users_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='ix_users_role'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined'], name='ix_users_created_at'),
        ),
        migrations.AddIndex(
            model_name='authgoogleaccount',
            index=models.Index(fields=['user'], name='ix_auth_google_user'),
        ),
        migrations.AddIndex(
            model_name='authkakaoaccount',
            index=models.Index(fields=['user'], name='ix_auth_kakao_user'),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['user'], name='ix_user_addresses_user'),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['user', 'is_default'], name='ix_user_addr_default'),
        ),
    ]
