# Generated by Django 5.2.8 on 2025-12-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='delivery_memo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='배송 요청사항'),
        ),
    ]
