# Generated by Django 5.2.4 on 2025-11-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_groups_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(blank=True, help_text='이메일 인증 시 사용되는 인증 코드', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='이메일 주소 인증 완료 여부'),
        ),
        migrations.AlterField(
            model_name='user',
            name='provider',
            field=models.CharField(choices=[('email', '이메일'), ('google', '구글'), ('kakao', '카카오')], default='email', help_text='해당 계정을 마지막으로 로그인한 공급자', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='provider_id',
            field=models.CharField(blank=True, help_text='OAuth 공급자의 사용자 고유 ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Asia/Seoul', help_text='사용자 타임존 (IANA 포맷)', max_length=64),
        ),
    ]
