# Generated by Django 5.2.4 on 2025-12-25 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_add_delivery_memo_to_useraddress"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCategoryPreference",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="category_preference",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
                ("grain", models.SmallIntegerField(default=0, verbose_name="쌀/잡곡")),
                ("noodle_flour", models.SmallIntegerField(default=0, verbose_name="면/가루/베이커리")),
                ("vegetable", models.SmallIntegerField(default=0, verbose_name="채소/샐러드")),
                ("fruit", models.SmallIntegerField(default=0, verbose_name="과일")),
                ("bean_egg", models.SmallIntegerField(default=0, verbose_name="두부/콩/계란")),
                ("meat", models.SmallIntegerField(default=0, verbose_name="육류")),
                ("seafood", models.SmallIntegerField(default=0, verbose_name="수산물/해산물")),
                ("dairy", models.SmallIntegerField(default=0, verbose_name="우유/유제품")),
                ("kimchi_side", models.SmallIntegerField(default=0, verbose_name="김치/반찬")),
                ("seasoning_sauce_oil", models.SmallIntegerField(default=0, verbose_name="양념/소스/오일")),
                ("nut_dry_etc", models.SmallIntegerField(default=0, verbose_name="견과류/간식")),
                ("drink", models.SmallIntegerField(default=0, verbose_name="음료")),
                ("instant_food", models.SmallIntegerField(default=0, verbose_name="라면/간편식")),
                ("completed_at", models.DateTimeField(auto_now=True, verbose_name="완료 일시")),
            ],
            options={
                "verbose_name": "카테고리 선호도",
                "verbose_name_plural": "카테고리 선호도",
                "db_table": "user_category_preferences",
            },
        ),
    ]
