# Generated by Django 5.2.4 on 2025-12-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_add_user_category_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="authemailcredential",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="임시 비밀번호로 로그인 시 True, 비밀번호 변경 후 False",
                verbose_name="비밀번호 변경 필요",
            ),
        ),
        migrations.AddField(
            model_name="authemailcredential",
            name="temp_password_hash",
            field=models.CharField(
                blank=True,
                help_text="비밀번호 찾기로 발급된 임시 비밀번호",
                max_length=128,
                null=True,
                verbose_name="임시 비밀번호 해시",
            ),
        ),
        migrations.AddField(
            model_name="authemailcredential",
            name="temp_password_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="임시 비밀번호는 발급 후 30분간만 유효",
                null=True,
                verbose_name="임시 비밀번호 만료시각",
            ),
        ),
    ]
