# Generated by Django 5.2.8 on 2025-11-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_email_verification_code_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(blank=True, help_text='기존 버전 호환을 위한 이메일 인증 코드', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='provider',
            field=models.CharField(choices=[('email', '이메일'), ('google', '구글'), ('kakao', '카카오')], default='email', help_text='해당 계정이 마지막으로 로그인한 공급자', max_length=20),
        ),
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('password_hash', models.CharField(max_length=128)),
                ('verification_code', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '가입 대기',
                'verbose_name_plural': '가입 대기',
                'indexes': [models.Index(fields=['expires_at'], name='ix_pending_expires_at')],
            },
        ),
    ]
