# Generated by Django 5.2.8 on 2025-11-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_email_verification_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', '비회원'), ('user', '일반회원'), ('seller', '판매자'), ('admin', '관리자')], default='guest', max_length=20),
        ),
    ]
