# Generated by Django 5.2.8 on 2025-11-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='생년월일', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='회원 탈퇴 일시 (소프트 삭제)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '남성'), ('female', '여성'), ('other', '기타'), ('prefer_not_to_say', '선택 안함')], help_text='성별', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='ko', help_text='선호 언어 (ko, en 등)', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='marketing_agreed',
            field=models.BooleanField(default=False, help_text='마케팅 정보 수신 동의'),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_enabled',
            field=models.BooleanField(default=True, help_text='알림 수신 여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='전화번호 (향후 인증용)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='provider',
            field=models.CharField(choices=[('email', '이메일'), ('google', '구글'), ('kakao', '카카오'), ('naver', '네이버'), ('apple', '애플')], default='email', help_text='해당 계정이 마지막으로 로그인한 공급자', max_length=20),
        ),
    ]
