# Generated by Django 5.2.8 on 2025-11-23 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_date_of_birth_user_deleted_at_user_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='배송지명 (예: 집, 회사)', max_length=100)),
                ('recipient_name', models.CharField(help_text='수령인 이름', max_length=100)),
                ('recipient_phone', models.CharField(help_text='수령인 전화번호', max_length=20)),
                ('postal_code', models.CharField(help_text='우편번호', max_length=10)),
                ('address_line1', models.CharField(help_text='기본 주소', max_length=255)),
                ('address_line2', models.CharField(blank=True, help_text='상세 주소', max_length=255, null=True)),
                ('city', models.CharField(help_text='시/도', max_length=100)),
                ('state', models.CharField(help_text='구/군', max_length=100)),
                ('country', models.CharField(default='KR', help_text='국가 코드 (ISO 3166-1 alpha-2)', max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='위도', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='경도', max_digits=11, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='기본 배송지 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='배송지 소유자', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '배송지',
                'verbose_name_plural': '배송지',
                'db_table': 'user_addresses',
                'indexes': [models.Index(fields=['user', 'is_default'], name='ix_user_addr_user_default')],
            },
        ),
    ]
