# Generated by Django 5.2.8 on 2025-11-23 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_useraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('credit_card', '신용카드'), ('debit_card', '체크카드'), ('bank_account', '계좌이체'), ('virtual_account', '가상계좌'), ('mobile', '간편결제')], help_text='결제 수단 유형', max_length=20)),
                ('provider', models.CharField(help_text='결제 제공자 (kakaopay, tosspay, card 등)', max_length=50)),
                ('card_number_last4', models.CharField(blank=True, help_text='카드 번호 마지막 4자리', max_length=4, null=True)),
                ('card_issuer', models.CharField(blank=True, help_text='카드 발급사', max_length=50, null=True)),
                ('card_type', models.CharField(blank=True, help_text='카드 종류 (credit, debit, prepaid)', max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, help_text='은행명', max_length=50, null=True)),
                ('account_number_last4', models.CharField(blank=True, help_text='계좌번호 마지막 4자리', max_length=4, null=True)),
                ('payment_gateway_token', models.TextField(blank=True, help_text='PG사 빌링키 (나중에 암호화 필요)', null=True)),
                ('is_default', models.BooleanField(default=False, help_text='기본 결제 수단 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='카드 유효기간', null=True)),
                ('user', models.ForeignKey(help_text='결제 수단 소유자', on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '결제 수단',
                'verbose_name_plural': '결제 수단',
                'db_table': 'user_payment_methods',
                'indexes': [models.Index(fields=['user', 'is_default'], name='ix_user_payment_user_default')],
            },
        ),
    ]
