server {
    listen 80;

    server_name sellfresh.shop www.sellfresh.shop;

    # HTTP 요청은 HTTPS로 리다이렉트
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name sellfresh.shop www.sellfresh.shop;

    # SSL 인증서 경로
    ssl_certificate /etc/letsencrypt/live/sellfresh.shop/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sellfresh.shop/privkey.pem;

    # TLS 설정
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    # API 요청 백엔드 프록시
    location /api {
        proxy_pass http://self-backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # OAuth 요청 백엔드 프록시
    location /auth {
        proxy_pass http://self-backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Frontend Admin Analytics (SPA)
    location ^~ /admin/analytics {
        try_files $uri $uri/ /index.html;
    }

    # Django Admin: 로그인/콘솔 백엔드 프록시
    location = /admin {
        proxy_pass http://self-backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ^~ /admin/ {
        proxy_pass http://self-backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Django Static 파일
    location /static {
        proxy_pass http://self-backend:8000;
        proxy_set_header Host $host;
    }
}
