# Generated by Django 5.2.8 on 2025-11-23 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0009_cart_wishlist'),
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='주문번호')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='받는분')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='연락처')),
                ('shipping_address', models.TextField(verbose_name='배송지')),
                ('shipping_memo', models.TextField(blank=True, null=True, verbose_name='배송 메모')),
                ('payment_method_type', models.CharField(default='card', max_length=20, verbose_name='결제 수단')),
                ('subtotal', models.IntegerField(default=0, verbose_name='상품 금액')),
                ('shipping_fee', models.IntegerField(default=0, verbose_name='배송비')),
                ('discount_amount', models.IntegerField(default=0, verbose_name='할인 금액')),
                ('total_amount', models.IntegerField(verbose_name='최종 결제 금액')),
                ('order_status', models.CharField(choices=[('pending', '주문대기'), ('paid', '결제완료'), ('processing', '처리중'), ('shipped', '배송중'), ('delivered', '배송완료'), ('cancelled', '취소'), ('refunded', '환불')], default='pending', max_length=20, verbose_name='주문 상태')),
                ('payment_status', models.CharField(choices=[('pending', '결제대기'), ('paid', '결제완료'), ('failed', '결제실패'), ('refunded', '환불완료'), ('partially_refunded', '부분환불')], default='pending', max_length=20, verbose_name='결제 상태')),
                ('payment_transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='결제 트랜잭션 ID')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='결제 시각')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='송장 번호')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='배송 시각')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='배송 완료 시각')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='취소 시각')),
                ('cancel_reason', models.TextField(blank=True, null=True, verbose_name='취소 사유')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='환불 시각')),
                ('refund_amount', models.IntegerField(default=0, verbose_name='환불 금액')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='주문자')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500, verbose_name='상품명')),
                ('product_image_url', models.TextField(blank=True, null=True, verbose_name='상품 이미지')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('unit_price', models.IntegerField(verbose_name='단가')),
                ('discount_amount', models.IntegerField(default=0, verbose_name='할인 금액')),
                ('total_price', models.IntegerField(verbose_name='총 가격')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='주문')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_items', to='products.product', verbose_name='상품')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='sellers.seller', verbose_name='판매자')),
            ],
            options={
                'verbose_name': '주문 상품',
                'verbose_name_plural': '주문 상품',
                'db_table': 'order_items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='orders_user_id_535113_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_order_n_1336be_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_status'], name='orders_order_s_0d3802_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='orders_payment_050188_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='order_items_order_i_26ad88_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='order_items_product_a53db1_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['seller'], name='order_items_seller__0dab98_idx'),
        ),
    ]
