# Generated by Django 5.2.8 on 2025-12-01 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('card', '카드'), ('bank_transfer', '계좌이체'), ('virtual_account', '가상계좌'), ('mobile', '간편결제'), ('other', '기타')], default='card', max_length=20, verbose_name='결제 수단')),
                ('amount', models.IntegerField(verbose_name='결제 금액')),
                ('status', models.CharField(choices=[('pending', '대기'), ('success', '성공'), ('failed', '실패'), ('cancelled', '취소')], default='pending', max_length=20, verbose_name='결제 상태')),
                ('is_simulation', models.BooleanField(default=True, verbose_name='시뮬레이션 여부')),
                ('simulation_note', models.TextField(blank=True, null=True, verbose_name='시뮬레이션 메모')),
                ('pg_provider', models.CharField(blank=True, max_length=50, null=True, verbose_name='PG사')),
                ('pg_tid', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='PG 트랜잭션 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리 시각')),
                ('failure_reason', models.TextField(blank=True, null=True, verbose_name='실패 사유')),
            ],
            options={
                'verbose_name': '결제',
                'verbose_name_plural': '결제',
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='수령인 이름')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='수령인 전화번호')),
                ('address_full', models.CharField(max_length=500, verbose_name='전체 주소')),
                ('shipping_memo', models.TextField(blank=True, null=True, verbose_name='배송 메모')),
                ('courier', models.CharField(blank=True, max_length=50, null=True, verbose_name='택배사')),
                ('tracking_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='송장 번호')),
                ('shipping_fee', models.IntegerField(default=0, verbose_name='배송비')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='출하 시각')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='배송완료 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '배송',
                'verbose_name_plural': '배송',
                'db_table': 'shipments',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='주문번호')),
                ('status', models.CharField(choices=[('pending', '주문대기'), ('paid', '결제완료'), ('processing', '처리중'), ('shipped', '배송중'), ('delivered', '배송완료'), ('cancelled', '취소'), ('refunded', '환불')], default='pending', max_length=20, verbose_name='주문 상태')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='취소 시각')),
                ('cancel_reason', models.TextField(blank=True, null=True, verbose_name='취소 사유')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='환불 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='주문자')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_snapshot', models.CharField(max_length=500, verbose_name='상품명 스냅샷')),
                ('unit_price_snapshot', models.IntegerField(verbose_name='단가 스냅샷')),
                ('quantity', models.IntegerField(verbose_name='수량')),
                ('discount_amount', models.IntegerField(default=0, verbose_name='할인 금액')),
                ('status', models.CharField(choices=[('pending', '대기'), ('paid', '결제완료'), ('shipping', '배송중'), ('delivered', '배송완료'), ('cancelled', '취소'), ('refunded', '환불')], default='pending', max_length=20, verbose_name='품목 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='주문')),
            ],
            options={
                'verbose_name': '주문 품목',
                'verbose_name_plural': '주문 품목',
                'db_table': 'order_items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
