# Generated by Django 5.2.8 on 2025-12-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_guest_order_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inventory_deducted',
            field=models.BooleanField(default=False, help_text='주문 생성 시 재고가 차감되었는지 여부 (취소 시 복원 판단용)', verbose_name='재고 차감 여부'),
        ),
    ]
