# Generated by Django 5.2.8 on 2025-12-24 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_add_seller_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('request', '결제 요청'), ('confirm', '결제 승인'), ('cancel', '결제 취소'), ('webhook', '웹훅 수신'), ('error', '오류')], max_length=20, verbose_name='로그 유형')),
                ('request_data', models.JSONField(blank=True, null=True, verbose_name='요청 데이터')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='응답 데이터')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='에러 메시지')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '결제 로그',
                'verbose_name_plural': '결제 로그',
                'db_table': 'payment_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='card_company',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='카드사'),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_installment_months',
            field=models.IntegerField(blank=True, help_text='0 = 일시불', null=True, verbose_name='할부 개월수'),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_number_masked',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='마스킹된 카드번호'),
        ),
        migrations.AddField(
            model_name='payment',
            name='expected_amount',
            field=models.IntegerField(blank=True, help_text='결제 요청 시 저장, 승인 시 검증하여 위변조 방지', null=True, verbose_name='예상 결제 금액'),
        ),
        migrations.AddField(
            model_name='payment',
            name='pg_order_id',
            field=models.CharField(blank=True, db_index=True, help_text='토스페이먼츠 orderId (결제 승인 시 검증용)', max_length=64, null=True, verbose_name='토스 주문ID'),
        ),
        migrations.AddField(
            model_name='payment',
            name='pg_raw_response',
            field=models.JSONField(blank=True, help_text='토스페이먼츠 API 원본 응답 저장 (디버깅/감사용)', null=True, verbose_name='PG 원본 응답'),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_amount',
            field=models.IntegerField(default=0, verbose_name='환불 금액'),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='환불 처리 시각'),
        ),
        migrations.AddField(
            model_name='payment',
            name='virtual_account_bank',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='가상계좌 은행'),
        ),
        migrations.AddField(
            model_name='payment',
            name='virtual_account_due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='가상계좌 입금 기한'),
        ),
        migrations.AddField(
            model_name='payment',
            name='virtual_account_holder',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='가상계좌 예금주'),
        ),
        migrations.AddField(
            model_name='payment',
            name='virtual_account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='가상계좌 번호'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method_type',
            field=models.CharField(choices=[('card', '카드'), ('bank_transfer', '계좌이체'), ('virtual_account', '가상계좌'), ('mobile', '휴대폰결제'), ('other', '기타'), ('pending', '결제대기')], default='card', max_length=20, verbose_name='결제 수단'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pg_tid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='PG 트랜잭션 ID (paymentKey)'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['pg_order_id'], name='ix_payments_pg_order_id'),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='orders.payment', verbose_name='결제'),
        ),
        migrations.AddIndex(
            model_name='paymentlog',
            index=models.Index(fields=['payment'], name='ix_payment_logs_payment'),
        ),
        migrations.AddIndex(
            model_name='paymentlog',
            index=models.Index(fields=['log_type'], name='ix_payment_logs_type'),
        ),
        migrations.AddIndex(
            model_name='paymentlog',
            index=models.Index(fields=['created_at'], name='ix_payment_logs_created'),
        ),
    ]
