# Generated by Django 5.2.8 on 2025-12-01 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200, unique=True, verbose_name='브랜드명')),
                ('brand_slug', models.SlugField(max_length=200, unique=True, verbose_name='브랜드 슬러그')),
                ('brand_logo_url', models.TextField(blank=True, null=True, verbose_name='브랜드 로고 URL')),
                ('brand_description', models.TextField(blank=True, null=True, verbose_name='브랜드 설명')),
                ('status', models.CharField(choices=[('pending', '승인대기'), ('active', '활성'), ('suspended', '정지'), ('inactive', '비활성')], default='pending', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '판매자',
                'verbose_name_plural': '판매자',
                'db_table': 'sellers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerBusiness',
            fields=[
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='business', serialize=False, to='sellers.seller', verbose_name='판매자')),
                ('registration_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='사업자등록번호')),
                ('business_type', models.CharField(blank=True, choices=[('individual', '개인사업자'), ('corporate', '법인사업자'), ('cooperative', '협동조합')], max_length=20, null=True, verbose_name='사업자 유형')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='회사명')),
                ('ceo_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='대표자명')),
                ('business_address', models.TextField(blank=True, null=True, verbose_name='사업장 주소')),
                ('cs_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='고객센터 전화번호')),
                ('verification_doc_url', models.TextField(blank=True, null=True, verbose_name='인증 서류 URL')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='인증일시')),
            ],
            options={
                'verbose_name': '판매자 사업자 정보',
                'verbose_name_plural': '판매자 사업자 정보',
                'db_table': 'seller_businesses',
            },
        ),
        migrations.CreateModel(
            name='SellerSettlement',
            fields=[
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settlement', serialize=False, to='sellers.seller', verbose_name='판매자')),
                ('bank_name', models.CharField(max_length=50, verbose_name='은행명')),
                ('account_number', models.CharField(max_length=50, verbose_name='계좌번호')),
                ('account_holder', models.CharField(max_length=100, verbose_name='예금주')),
            ],
            options={
                'verbose_name': '판매자 정산 계좌',
                'verbose_name_plural': '판매자 정산 계좌',
                'db_table': 'seller_settlements',
            },
        ),
        migrations.CreateModel(
            name='SellerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.SmallIntegerField(choices=[(0, '월요일'), (1, '화요일'), (2, '수요일'), (3, '목요일'), (4, '금요일'), (5, '토요일'), (6, '일요일')], verbose_name='요일')),
                ('open_time', models.TimeField(verbose_name='오픈 시간')),
                ('close_time', models.TimeField(verbose_name='마감 시간')),
                ('is_holiday', models.BooleanField(default=False, verbose_name='휴무일 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='sellers.seller', verbose_name='판매자')),
            ],
            options={
                'verbose_name': '영업시간',
                'verbose_name_plural': '영업시간',
                'db_table': 'seller_schedules',
                'ordering': ['seller', 'day_of_week'],
            },
        ),
        migrations.AddIndex(
            model_name='seller',
            index=models.Index(fields=['user'], name='ix_sellers_user'),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=models.Index(fields=['brand_slug'], name='ix_sellers_brand_slug'),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=models.Index(fields=['status'], name='ix_sellers_status'),
        ),
        migrations.AddIndex(
            model_name='sellerschedule',
            index=models.Index(fields=['seller', 'day_of_week'], name='ix_seller_schedules'),
        ),
        migrations.AlterUniqueTogether(
            name='sellerschedule',
            unique_together={('seller', 'day_of_week')},
        ),
    ]
