# Generated by Django 5.2.8 on 2025-11-23 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200, unique=True, verbose_name='브랜드명')),
                ('brand_name_en', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='브랜드명(영문)')),
                ('brand_slug', models.SlugField(max_length=200, unique=True, verbose_name='브랜드 슬러그')),
                ('brand_description', models.TextField(blank=True, null=True, verbose_name='브랜드 설명')),
                ('brand_logo_url', models.TextField(blank=True, null=True, verbose_name='브랜드 로고 URL')),
                ('brand_banner_url', models.TextField(blank=True, null=True, verbose_name='브랜드 배너 URL')),
                ('business_registration_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='사업자등록번호')),
                ('business_type', models.CharField(blank=True, choices=[('individual', '개인사업자'), ('corporate', '법인사업자'), ('cooperative', '협동조합')], max_length=20, null=True, verbose_name='사업자 유형')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='회사명')),
                ('ceo_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='대표자명')),
                ('is_verified', models.BooleanField(default=False, verbose_name='인증 여부')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='인증일시')),
                ('verification_document_url', models.TextField(blank=True, null=True, verbose_name='인증 서류 URL')),
                ('business_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='사업장 전화번호')),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='사업장 이메일')),
                ('customer_service_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='고객센터 전화번호')),
                ('business_address', models.TextField(blank=True, null=True, verbose_name='사업장 주소')),
                ('warehouse_address', models.TextField(blank=True, null=True, verbose_name='창고 주소')),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='은행명')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='계좌번호')),
                ('account_holder_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='예금주명')),
                ('min_order_amount', models.IntegerField(default=0, verbose_name='최소 주문 금액')),
                ('shipping_fee', models.IntegerField(default=0, verbose_name='기본 배송비')),
                ('free_shipping_threshold', models.IntegerField(blank=True, null=True, verbose_name='무료 배송 기준 금액')),
                ('total_products', models.IntegerField(default=0, verbose_name='총 상품 수')),
                ('total_sales', models.IntegerField(default=0, verbose_name='총 판매액')),
                ('total_reviews', models.IntegerField(default=0, verbose_name='총 리뷰 수')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='평균 평점')),
                ('status', models.CharField(choices=[('pending', '승인대기'), ('active', '활성'), ('suspended', '정지'), ('inactive', '비활성')], default='pending', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '판매자',
                'verbose_name_plural': '판매자',
                'db_table': 'sellers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerOperatingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.SmallIntegerField(choices=[(0, '월요일'), (1, '화요일'), (2, '수요일'), (3, '목요일'), (4, '금요일'), (5, '토요일'), (6, '일요일')], verbose_name='요일')),
                ('open_time', models.TimeField(verbose_name='오픈 시간')),
                ('close_time', models.TimeField(verbose_name='마감 시간')),
                ('is_open', models.BooleanField(default=True, verbose_name='영업 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='sellers.seller', verbose_name='판매자')),
            ],
            options={
                'verbose_name': '영업시간',
                'verbose_name_plural': '영업시간',
                'db_table': 'seller_operating_hours',
                'ordering': ['seller', 'day_of_week'],
            },
        ),
        migrations.AddIndex(
            model_name='seller',
            index=models.Index(fields=['user'], name='sellers_user_id_9aef06_idx'),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=models.Index(fields=['brand_slug'], name='sellers_brand_s_5eb38f_idx'),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=models.Index(fields=['status'], name='sellers_status_150ab3_idx'),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=models.Index(fields=['is_verified'], name='sellers_is_veri_ef559e_idx'),
        ),
        migrations.AddIndex(
            model_name='selleroperatinghours',
            index=models.Index(fields=['seller'], name='seller_oper_seller__a1aac9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='selleroperatinghours',
            unique_together={('seller', 'day_of_week')},
        ),
    ]
