# Generated by Django 5.2.8 on 2025-12-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='brand_banner_url',
            field=models.TextField(blank=True, null=True, verbose_name='브랜드 배너 URL'),
        ),
        migrations.AddField(
            model_name='seller',
            name='profile_image_url',
            field=models.TextField(blank=True, null=True, verbose_name='판매자 프로필 이미지 URL'),
        ),
    ]
