# Generated by Django 5.2.8 on 2025-12-01 13:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_site', models.CharField(blank=True, help_text='초기 CSV/크롤링 출처 사이트 이름', max_length=100, null=True, verbose_name='출처 사이트')),
                ('source_url', models.TextField(blank=True, help_text='초기 CSV/크롤링 원본 상품 URL', null=True, verbose_name='출처 URL')),
                ('crawled_at', models.DateTimeField(blank=True, help_text='원본 데이터를 가져온 시각', null=True, verbose_name='크롤링 시각')),
                ('name', models.CharField(max_length=500, verbose_name='상품명')),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='슬러그')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='가격')),
                ('original_price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='원가')),
                ('status', models.CharField(choices=[('draft', '임시저장'), ('active', '판매중'), ('inactive', '판매중지'), ('out_of_stock', '품절'), ('discontinued', '단종')], default='active', max_length=20, verbose_name='상태')),
                ('product_type', models.CharField(choices=[('main', '메인 상품'), ('seller', '판매자 상품')], default='main', max_length=20, verbose_name='상품 유형')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='단위')),
                ('unit_quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='단위 수량')),
                ('shipping_required', models.BooleanField(default=True, verbose_name='배송 필요')),
                ('shipping_fee', models.IntegerField(default=0, verbose_name='배송비')),
                ('free_shipping_threshold', models.IntegerField(blank=True, null=True, verbose_name='무료 배송 기준 금액')),
                ('estimated_delivery_days', models.SmallIntegerField(blank=True, null=True, verbose_name='예상 배송 일수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리명')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='슬러그')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='상위 카테고리')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detail', serialize=False, to='products.product', verbose_name='상품')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='짧은 설명')),
                ('full_description', models.TextField(blank=True, null=True, verbose_name='상세 설명')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO 제목')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='SEO 키워드')),
            ],
            options={
                'verbose_name': '상품 상세',
                'verbose_name_plural': '상품 상세',
                'db_table': 'product_details',
            },
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='inventory', serialize=False, to='products.product', verbose_name='상품')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='재고 수량')),
                ('safe_stock_level', models.IntegerField(default=10, verbose_name='안전 재고 수준')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '상품 재고',
                'verbose_name_plural': '상품 재고',
                'db_table': 'product_inventories',
            },
        ),
        migrations.CreateModel(
            name='ProductStats',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to='products.product', verbose_name='상품')),
                ('view_count', models.BigIntegerField(default=0, verbose_name='조회수')),
                ('recommend_clicked_count', models.BigIntegerField(default=0, verbose_name='추천 클릭수')),
                ('cart_event_count', models.BigIntegerField(default=0, verbose_name='장바구니 이벤트 수')),
                ('order_event_count', models.BigIntegerField(default=0, verbose_name='주문 이벤트 수')),
                ('wishlist_count', models.BigIntegerField(default=0, verbose_name='찜 수')),
                ('review_count', models.BigIntegerField(default=0, verbose_name='리뷰 수')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='평균 평점')),
                ('photo_review_count', models.BigIntegerField(default=0, verbose_name='사진 리뷰 수')),
                ('sentiment_score_avg', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='감성 점수 평균')),
                ('first_review_at', models.DateTimeField(blank=True, null=True, verbose_name='첫 리뷰 시각')),
                ('quality_score', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='품질 점수')),
                ('image_quality_score', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='이미지 품질 점수')),
                ('content_quality_score', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='콘텐츠 품질 점수')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='갱신 시각')),
            ],
            options={
                'verbose_name': '상품 통계',
                'verbose_name_plural': '상품 통계',
                'db_table': 'product_stats',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sellers.seller', verbose_name='판매자'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='수량')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_carts', to='products.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '장바구니',
                'verbose_name_plural': '장바구니',
                'db_table': 'carts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField(verbose_name='이미지 URL')),
                ('display_order', models.IntegerField(default=0, verbose_name='표시 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '상품 이미지',
                'verbose_name_plural': '상품 이미지',
                'db_table': 'product_images',
                'ordering': ['product', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='평점')),
                ('content', models.TextField(verbose_name='리뷰 내용')),
                ('has_photos', models.BooleanField(default=False, verbose_name='사진 리뷰 여부')),
                ('status', models.CharField(choices=[('visible', '공개'), ('hidden', '숨김'), ('reported', '신고됨'), ('deleted', '삭제됨')], default='visible', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='orders.orderitem', verbose_name='주문 품목')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='상품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '리뷰',
                'verbose_name_plural': '리뷰',
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField(verbose_name='이미지 URL')),
                ('display_order', models.IntegerField(default=0, verbose_name='표시 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.review', verbose_name='리뷰')),
            ],
            options={
                'verbose_name': '리뷰 이미지',
                'verbose_name_plural': '리뷰 이미지',
                'db_table': 'review_images',
            },
        ),
        migrations.CreateModel(
            name='SellerFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='팔로우 시각')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='sellers.seller', verbose_name='판매자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_sellers', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '판매자 팔로우',
                'verbose_name_plural': '판매자 팔로우',
                'db_table': 'seller_follows',
            },
        ),
        migrations.CreateModel(
            name='UserProductStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.BigIntegerField(default=0, verbose_name='조회수')),
                ('cart_event_count', models.BigIntegerField(default=0, verbose_name='장바구니 이벤트 수')),
                ('order_event_count', models.BigIntegerField(default=0, verbose_name='주문 이벤트 수')),
                ('last_interacted_at', models.DateTimeField(auto_now=True, verbose_name='마지막 상호작용 시각')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='products.product', verbose_name='상품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stats', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '유저별 상품 통계',
                'verbose_name_plural': '유저별 상품 통계',
                'db_table': 'user_product_stats',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='추가일시')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='products.product', verbose_name='상품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '찜 목록',
                'verbose_name_plural': '찜 목록',
                'db_table': 'wishlists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='ix_categories_parent'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller'], name='ix_products_seller'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='ix_products_category'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='ix_products_status'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='ix_products_type'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='ix_products_slug'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='ix_products_created'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', '-created_at'], name='ix_carts_user'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'product')},
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'display_order'], name='ix_product_images_order'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product'], name='ix_reviews_product'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user'], name='ix_reviews_user'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['order_item'], name='ix_reviews_order_item'),
        ),
        migrations.AddIndex(
            model_name='reviewimage',
            index=models.Index(fields=['review', 'display_order'], name='ix_review_images_order'),
        ),
        migrations.AddIndex(
            model_name='sellerfollow',
            index=models.Index(fields=['user', 'seller'], name='ix_seller_follows_pair'),
        ),
        migrations.AddIndex(
            model_name='sellerfollow',
            index=models.Index(fields=['user'], name='ix_seller_follows_user'),
        ),
        migrations.AddIndex(
            model_name='sellerfollow',
            index=models.Index(fields=['seller'], name='ix_seller_follows_seller'),
        ),
        migrations.AlterUniqueTogether(
            name='sellerfollow',
            unique_together={('user', 'seller')},
        ),
        migrations.AddIndex(
            model_name='userproductstats',
            index=models.Index(fields=['user', 'product'], name='ix_user_product_stats_pair'),
        ),
        migrations.AddIndex(
            model_name='userproductstats',
            index=models.Index(fields=['user'], name='ix_user_product_stats_user'),
        ),
        migrations.AddIndex(
            model_name='userproductstats',
            index=models.Index(fields=['product'], name='ix_user_product_stats_product'),
        ),
        migrations.AlterUniqueTogether(
            name='userproductstats',
            unique_together={('user', 'product')},
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user', '-created_at'], name='ix_wishlists_user'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'product')},
        ),
    ]
