# Generated by Django 5.2.8 on 2025-11-23 07:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='카테고리명')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='슬러그')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='출처')),
                ('name', models.CharField(max_length=500, verbose_name='제품명')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='가격')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='단위')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('product_url', models.TextField(blank=True, null=True, verbose_name='제품 URL')),
                ('image_url', models.TextField(verbose_name='이미지 URL')),
                ('detail_info', models.TextField(blank=True, null=True, verbose_name='상세정보')),
                ('crawled_at', models.DateTimeField(blank=True, null=True, verbose_name='크롤링 시간')),
                ('original_price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='원가')),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='할인율')),
                ('is_best', models.BooleanField(default=False, verbose_name='베스트')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '제품',
                'verbose_name_plural': '제품',
                'db_table': 'products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='products_categor_4083ff_idx'), models.Index(fields=['price'], name='products_price_fe467e_idx'), models.Index(fields=['name'], name='products_name_6f9890_idx')],
            },
        ),
    ]
