# Generated by Django 5.2.8 on 2025-11-23 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['path'], 'verbose_name': '카테고리', 'verbose_name_plural': '카테고리'},
        ),
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.SmallIntegerField(db_index=True, default=0, editable=False, verbose_name='레벨'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='상위 카테고리'),
        ),
        migrations.AddField(
            model_name='category',
            name='path',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=500, null=True, verbose_name='경로'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='카테고리명'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='슬러그'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent', 'name')},
        ),
    ]
