# Generated by Django 5.2.8 on 2025-12-01 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(help_text='해당 시점의 가격', verbose_name='가격')),
                ('original_price', models.IntegerField(blank=True, help_text='해당 시점의 원가 (할인 전 가격)', null=True, verbose_name='원가')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='가격이 기록된 시각', verbose_name='기록 시각')),
                ('source', models.CharField(blank=True, help_text='가격 변경 출처 (import, manual, crawl 등)', max_length=50, null=True, verbose_name='변경 출처')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='products.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '상품 가격 이력',
                'verbose_name_plural': '상품 가격 이력',
                'db_table': 'product_price_histories',
                'ordering': ['product', '-recorded_at'],
                'indexes': [models.Index(fields=['product', '-recorded_at'], name='ix_price_history_product'), models.Index(fields=['recorded_at'], name='ix_price_history_recorded')],
            },
        ),
    ]
