# Generated by Django 5.2.8 on 2025-12-07 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_product_price_history'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='sellers.seller', verbose_name='판매자'),
        ),
    ]
