# Generated by Django 5.2.8 on 2025-11-23 12:21

from django.db import migrations


def populate_category_paths(apps, schema_editor):
    """기존 카테고리들의 path와 level 값 채우기"""
    Category = apps.get_model('products', 'Category')

    # 모든 카테고리는 parent가 없으므로 (최초 상태) 모두 루트 카테고리로 처리
    for category in Category.objects.all():
        category.path = category.slug
        category.level = 0
        category.save(update_fields=['path', 'level'])


def reverse_populate(apps, schema_editor):
    """되돌리기: path와 level을 NULL로 설정"""
    Category = apps.get_model('products', 'Category')
    Category.objects.all().update(path=None, level=0)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_category_level_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_category_paths, reverse_populate),
    ]
