# Generated by Django 5.2.8 on 2025-11-23 12:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_populate_category_paths'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_price_fe467e_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_name_6f9890_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='평균 평점'),
        ),
        migrations.AddField(
            model_name='product',
            name='cart_count',
            field=models.IntegerField(default=0, verbose_name='장바구니 추가수'),
        ),
        migrations.AddField(
            model_name='product',
            name='click_count',
            field=models.IntegerField(default=0, verbose_name='클릭수'),
        ),
        migrations.AddField(
            model_name='product',
            name='content_quality_score',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='콘텐츠 품질 점수'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='원가 (판매자용)'),
        ),
        migrations.AddField(
            model_name='product',
            name='ctr',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='click_count / view_count', max_digits=5, verbose_name='CTR'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_rate',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='할인율'),
        ),
        migrations.AddField(
            model_name='product',
            name='estimated_delivery_days',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='예상 배송 일수'),
        ),
        migrations.AddField(
            model_name='product',
            name='free_shipping_threshold',
            field=models.IntegerField(blank=True, null=True, verbose_name='무료 배송 기준 금액'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_quality_score',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='이미지 품질 점수'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='추천 상품'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_in_stock',
            field=models.BooleanField(default=True, verbose_name='재고 있음'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='신상품'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False, verbose_name='할인 중'),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.IntegerField(default=10, verbose_name='낮은 재고 기준'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image_url',
            field=models.TextField(blank=True, null=True, verbose_name='메인 이미지 URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='SEO 설명'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='SEO 키워드'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO 제목'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('main', '메인 상품'), ('seller', '판매자 상품')], default='main', max_length=20, verbose_name='상품 유형'),
        ),
        migrations.AddField(
            model_name='product',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='게시일시'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_count',
            field=models.IntegerField(default=0, verbose_name='구매수'),
        ),
        migrations.AddField(
            model_name='product',
            name='quality_score',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='이미지 품질, 설명 완성도, CTR 등을 종합', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='품질 점수'),
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.IntegerField(default=0, verbose_name='리뷰수'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, help_text="product_type='seller'일 때만 필수", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sellers.seller', verbose_name='판매자'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_fee',
            field=models.IntegerField(default=0, verbose_name='배송비'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_required',
            field=models.BooleanField(default=True, verbose_name='배송 필요'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='간단 설명'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True, verbose_name='슬러그'),
        ),
        migrations.AddField(
            model_name='product',
            name='source_site',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='출처 사이트'),
        ),
        migrations.AddField(
            model_name='product',
            name='source_url',
            field=models.TextField(blank=True, null=True, verbose_name='출처 URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', '임시저장'), ('active', '판매중'), ('inactive', '판매중지'), ('out_of_stock', '품절'), ('discontinued', '단종')], default='active', max_length=20, verbose_name='상태'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, verbose_name='재고 수량'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='단위 수량'),
        ),
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AddField(
            model_name='product',
            name='wishlist_count',
            field=models.IntegerField(default=0, verbose_name='찜 수'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='상세 설명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail_info',
            field=models.TextField(blank=True, null=True, verbose_name='[DEPRECATED] 상세정보'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='[DEPRECATED] 할인율'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.TextField(blank=True, null=True, verbose_name='[DEPRECATED] 이미지 URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_best',
            field=models.BooleanField(default=False, verbose_name='베스트 상품'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.TextField(blank=True, null=True, verbose_name='[DEPRECATED] 제품 URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='site_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='[DEPRECATED] 출처'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='products_product_af48aa_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller'], name='products_seller__c70854_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='products_status_a30e64_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-quality_score'], name='products_quality_0e772b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-view_count'], name='products_view_co_181adc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-ctr'], name='products_ctr_f0ded5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='products_created_a77fb9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'status'], name='products_is_feat_a3b38e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_best', 'status'], name='products_is_best_b38239_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_slug_5e91f2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type', 'status', '-quality_score', '-ctr'], name='products_product_78d2ab_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status', '-quality_score'], name='products_categor_320389_idx'),
        ),
    ]
