# Generated by Django 5.2.8 on 2025-12-08 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_optimize_price_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userproductstats',
            index=models.Index(fields=['user', '-last_interacted_at'], name='ix_ups_user_recent'),
        ),
    ]
