# Generated by Django 5.2.8 on 2025-11-23 12:30

from django.db import migrations


def copy_old_product_data(apps, schema_editor):
    """이전 CSV 필드에서 새 필드로 데이터 복사"""
    Product = apps.get_model('products', 'Product')

    for product in Product.objects.all():
        # image_url → main_image_url
        if product.image_url:
            product.main_image_url = product.image_url

        # site_name → source_site
        if product.site_name:
            product.source_site = product.site_name

        # product_url → source_url
        if product.product_url:
            product.source_url = product.product_url

        # detail_info → description (detail_info를 description에 추가)
        if product.detail_info and not product.description:
            product.description = product.detail_info

        # discount → discount_rate
        if product.discount is not None:
            product.discount_rate = product.discount

        product.save(update_fields=['main_image_url', 'source_site', 'source_url', 'description', 'discount_rate'])


def reverse_copy(apps, schema_editor):
    """되돌리기: 새 필드에서 이전 필드로 데이터 복사"""
    Product = apps.get_model('products', 'Product')

    for product in Product.objects.all():
        if product.main_image_url:
            product.image_url = product.main_image_url
        if product.source_site:
            product.site_name = product.source_site
        if product.source_url:
            product.product_url = product.source_url
        if product.discount_rate is not None:
            product.discount = product.discount_rate

        product.save(update_fields=['image_url', 'site_name', 'product_url', 'discount'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_products_price_fe467e_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_old_product_data, reverse_copy),
    ]
