# Generated by Django 5.2.8 on 2025-12-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_inventory_is_unlimited'),
        ('products', '0005_add_user_recent_index'),
    ]

    operations = [
    ]
