# Generated by Django 5.2.8 on 2025-11-23 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_copy_old_product_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField(verbose_name='이미지 URL')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='대체 텍스트')),
                ('display_order', models.IntegerField(default=0, verbose_name='표시 순서')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='너비')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='높이')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='파일 크기 (bytes)')),
                ('format', models.CharField(blank=True, max_length=10, null=True, verbose_name='형식')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '상품 이미지',
                'verbose_name_plural': '상품 이미지',
                'db_table': 'product_images',
                'ordering': ['product', 'display_order'],
                'indexes': [models.Index(fields=['product', 'display_order'], name='product_ima_product_d1c257_idx')],
            },
        ),
    ]
