# Generated by Django 5.2.8 on 2025-11-23 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='세션 ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('referrer', models.TextField(blank=True, null=True, verbose_name='Referrer')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='조회 시간')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='products.product', verbose_name='상품')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_views', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '상품 조회 로그',
                'verbose_name_plural': '상품 조회 로그',
                'db_table': 'product_views',
                'indexes': [models.Index(fields=['product', '-viewed_at'], name='product_vie_product_e08eaa_idx'), models.Index(fields=['user', '-viewed_at'], name='product_vie_user_id_6e993a_idx'), models.Index(fields=['session_id', '-viewed_at'], name='product_vie_session_0affb3_idx')],
            },
        ),
    ]
