# Generated by Django 5.2.4 on 2025-12-20 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_add_detail_full_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySalesStats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(help_text="판매가 발생한 날짜", verbose_name="날짜")),
                (
                    "order_count",
                    models.IntegerField(
                        default=0,
                        help_text="해당 날짜의 주문 건수 (quantity가 아닌 주문 횟수)",
                        verbose_name="주문 횟수",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_sales",
                        to="products.product",
                        verbose_name="상품",
                    ),
                ),
            ],
            options={
                "verbose_name": "일일 판매 통계",
                "verbose_name_plural": "일일 판매 통계",
                "db_table": "daily_sales_stats",
                "indexes": [
                    models.Index(fields=["date", "-order_count"], name="ix_dss_date_order"),
                    models.Index(fields=["product", "date"], name="ix_dss_product_date"),
                ],
                "unique_together": {("product", "date")},
            },
        ),
    ]
