# Generated by Django 5.2.4 on 2025-12-22
# parsed_ingredients 필드 추가: GMS 재료 추출 결과 저장용

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_add_daily_sales_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parsed_ingredients',
            field=models.JSONField(
                blank=True,
                null=True,
                verbose_name='파싱된 재료 정보',
                help_text='GMS(GPT)로 추출된 상품명 분석 결과 (main_ingredient, normalized_ingredient, brand, weight 등)',
            ),
        ),
    ]
