# Generated by Django 5.2.4 on 2025-12-22
# parsed_ingredients JSON 필드에 GIN 인덱스 추가 (PostgreSQL 전용)

from django.db import migrations, connection


def add_gin_index(apps, schema_editor):
    """PostgreSQL에서만 GIN 인덱스 생성"""
    if connection.vendor == 'postgresql':
        # Django 커스텀 테이블명 사용 (db_table='products')
        schema_editor.execute(
            """
            CREATE INDEX IF NOT EXISTS ix_products_parsed_gin
            ON products USING GIN (parsed_ingredients)
            """
        )


def remove_gin_index(apps, schema_editor):
    """PostgreSQL에서만 GIN 인덱스 삭제"""
    if connection.vendor == 'postgresql':
        schema_editor.execute(
            "DROP INDEX IF EXISTS ix_products_parsed_gin"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_add_parsed_ingredients'),
    ]

    operations = [
        # PostgreSQL GIN 인덱스: JSON 내부 키 검색 최적화
        # SQLite 등 다른 DB에서는 무시됨
        migrations.RunPython(
            add_gin_index,
            remove_gin_index,
        ),
    ]
