# Generated by Django 5.2.4 on 2025-12-22
# parsed_ingredients JSON 필드에 GIN 인덱스 추가 (PostgreSQL 전용)

from django.db import migrations
from django.contrib.postgres.indexes import GinIndex


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_add_parsed_ingredients'),
    ]

    operations = [
        # PostgreSQL GIN 인덱스: JSON 내부 키 검색 최적화
        # normalized_ingredient, main_ingredient 기반 조회 성능 향상
        migrations.AddIndex(
            model_name='product',
            index=GinIndex(
                fields=['parsed_ingredients'],
                name='ix_products_parsed_gin',
            ),
        ),
    ]
