# Generated by Django 5.2.4
# 상품 조회 로그 테이블 (조회수 쿨타임 관리용)

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """ProductViewLog 테이블 생성

    조회수 어뷰징 방지를 위한 쿨타임(2분) 관리 테이블.
    - 회원: user_id 기반 추적
    - 비회원: IP + User-Agent 해시 기반 추적
    """

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0010_add_parsed_ingredients_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductViewLog',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('visitor_hash', models.CharField(
                    blank=True,
                    help_text='비회원: SHA256(IP + User-Agent), 회원: NULL',
                    max_length=64,
                    null=True,
                    verbose_name='방문자 해시'
                )),
                ('ip_address', models.GenericIPAddressField(
                    blank=True,
                    null=True,
                    verbose_name='IP 주소'
                )),
                ('viewed_at', models.DateTimeField(
                    auto_now_add=True,
                    verbose_name='조회 시각'
                )),
                ('product', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='view_logs',
                    to='products.product',
                    verbose_name='상품'
                )),
                ('user', models.ForeignKey(
                    blank=True,
                    help_text='로그인 사용자인 경우 기록',
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='product_view_logs',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='사용자'
                )),
            ],
            options={
                'verbose_name': '상품 조회 로그',
                'verbose_name_plural': '상품 조회 로그',
                'db_table': 'product_view_logs',
            },
        ),
        # 회원 조회 쿨타임 체크용 인덱스
        migrations.AddIndex(
            model_name='productviewlog',
            index=models.Index(
                fields=['user', 'product', '-viewed_at'],
                name='ix_pvl_user_product_time'
            ),
        ),
        # 비회원 조회 쿨타임 체크용 인덱스
        migrations.AddIndex(
            model_name='productviewlog',
            index=models.Index(
                fields=['visitor_hash', 'product', '-viewed_at'],
                name='ix_pvl_visitor_product_time'
            ),
        ),
        # 오래된 로그 정리용 인덱스
        migrations.AddIndex(
            model_name='productviewlog',
            index=models.Index(
                fields=['viewed_at'],
                name='ix_pvl_viewed_at'
            ),
        ),
    ]
