# Generated by Django 5.2.4 on 2025-12-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBizDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='집계 날짜')),
                ('user_segment', models.CharField(choices=[('all', '전체'), ('consumer', '일반회원'), ('seller', '판매자')], default='all', max_length=20, verbose_name='유저 세그먼트')),
                ('sessions', models.BigIntegerField(default=0, help_text='세션 로그 도입 후 채워질 값 (초기에는 0 유지)', verbose_name='세션 수')),
                ('unique_buyers', models.BigIntegerField(default=0, verbose_name='구매 유저 수')),
                ('orders', models.BigIntegerField(default=0, verbose_name='주문 수')),
                ('gmv', models.BigIntegerField(default=0, verbose_name='총 매출(GMV)')),
                ('cart_adds', models.BigIntegerField(default=0, verbose_name='장바구니 담기 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': 'Admin 비즈니스 일간 집계',
                'verbose_name_plural': 'Admin 비즈니스 일간 집계',
                'db_table': 'admin_analytics_biz_daily',
                'indexes': [models.Index(fields=['date'], name='ix_abd_date'), models.Index(fields=['date', 'user_segment'], name='ix_abd_date_seg')],
                'constraints': [models.CheckConstraint(condition=models.Q(('sessions__gte', 0)), name='chk_admin_biz_daily_sessions_non_negative'), models.CheckConstraint(condition=models.Q(('unique_buyers__gte', 0)), name='chk_admin_biz_daily_unique_buyers_non_negative'), models.CheckConstraint(condition=models.Q(('orders__gte', 0)), name='chk_admin_biz_daily_orders_non_negative'), models.CheckConstraint(condition=models.Q(('gmv__gte', 0)), name='chk_admin_biz_daily_gmv_non_negative'), models.CheckConstraint(condition=models.Q(('cart_adds__gte', 0)), name='chk_admin_biz_daily_cart_adds_non_negative')],
                'unique_together': {('date', 'user_segment')},
            },
        ),
        migrations.CreateModel(
            name='AdminRecoDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='집계 날짜')),
                ('placement', models.CharField(help_text='home, detail_similar, cart_gapfill 등 추천 위치 식별자', max_length=50, verbose_name='추천 위치')),
                ('user_segment', models.CharField(choices=[('all', '전체'), ('consumer', '일반회원'), ('seller', '판매자')], default='all', max_length=20, verbose_name='유저 세그먼트')),
                ('reco_impressions', models.BigIntegerField(default=0, verbose_name='추천 노출 수')),
                ('reco_clicks', models.BigIntegerField(default=0, verbose_name='추천 클릭 수')),
                ('reco_attributed_orders', models.BigIntegerField(default=0, verbose_name='추천 기여 주문 수')),
                ('reco_attributed_gmv', models.BigIntegerField(default=0, verbose_name='추천 기여 매출(GMV)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': 'Admin 추천 일간 집계',
                'verbose_name_plural': 'Admin 추천 일간 집계',
                'db_table': 'admin_analytics_reco_daily',
                'indexes': [models.Index(fields=['date'], name='ix_ard_date'), models.Index(fields=['date', 'placement'], name='ix_ard_date_place'), models.Index(fields=['date', 'placement', 'user_segment'], name='ix_ard_date_place_seg')],
                'constraints': [models.CheckConstraint(condition=models.Q(('reco_impressions__gte', 0)), name='chk_admin_reco_daily_impr_non_negative'), models.CheckConstraint(condition=models.Q(('reco_clicks__gte', 0)), name='chk_admin_reco_daily_clicks_non_negative'), models.CheckConstraint(condition=models.Q(('reco_attributed_orders__gte', 0)), name='chk_admin_reco_daily_orders_non_negative'), models.CheckConstraint(condition=models.Q(('reco_attributed_gmv__gte', 0)), name='chk_admin_reco_daily_gmv_non_negative')],
                'unique_together': {('date', 'placement', 'user_segment')},
            },
        ),
    ]
