# Generated by Django 5.2.4 on 2025-12-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCategoryDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='집계 날짜')),
                ('user_segment', models.CharField(choices=[('all', '전체'), ('consumer', '일반회원'), ('seller', '판매자')], default='all', max_length=20, verbose_name='유저 세그먼트')),
                ('category_name', models.CharField(max_length=100, verbose_name='카테고리명')),
                ('sessions', models.BigIntegerField(default=0, verbose_name='세션 수')),
                ('orders', models.BigIntegerField(default=0, verbose_name='주문 수')),
                ('gmv', models.BigIntegerField(default=0, verbose_name='카테고리 매출(GMV)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': 'Admin 카테고리 일간 집계',
                'verbose_name_plural': 'Admin 카테고리 일간 집계',
                'db_table': 'admin_analytics_category_daily',
                'indexes': [models.Index(fields=['date'], name='ix_acd_date'), models.Index(fields=['date', 'user_segment'], name='ix_acd_date_seg'), models.Index(fields=['date', 'user_segment', 'category_name'], name='ix_acd_date_seg_cat')],
                'constraints': [models.CheckConstraint(condition=models.Q(('sessions__gte', 0)), name='chk_admin_cat_daily_sessions_non_negative'), models.CheckConstraint(condition=models.Q(('orders__gte', 0)), name='chk_admin_cat_daily_orders_non_negative'), models.CheckConstraint(condition=models.Q(('gmv__gte', 0)), name='chk_admin_cat_daily_gmv_non_negative')],
                'unique_together': {('date', 'user_segment', 'category_name')},
            },
        ),
    ]
