# Generated by Django 5.2.4 on 2025-12-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_add_is_test_flags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminbizdaily",
            name="is_test",
            field=models.BooleanField(
                default=False,
                help_text="샘플/시나리오 등 테스트용 집계 데이터인 경우 True 로 설정",
                verbose_name="테스트 데이터 여부",
            ),
        ),
        migrations.AlterField(
            model_name="adminbizdaily",
            name="scenario",
            field=models.CharField(
                blank=True,
                help_text="테스트 데이터 시나리오 구분값 (예: baseline/promo/high_abandon/loyal)",
                max_length=50,
                null=True,
                verbose_name="시나리오 태그",
            ),
        ),
        migrations.AlterField(
            model_name="admincategorydaily",
            name="is_test",
            field=models.BooleanField(
                default=False,
                help_text="샘플/시나리오 등 테스트용 카테고리 집계인 경우 True 로 설정",
                verbose_name="테스트 데이터 여부",
            ),
        ),
        migrations.AlterField(
            model_name="adminrecodaily",
            name="is_test",
            field=models.BooleanField(
                default=False,
                help_text="샘플/시나리오 등 테스트용 추천 집계인 경우 True 로 설정",
                verbose_name="테스트 데이터 여부",
            ),
        ),
    ]
