"""
Django settings for project_self project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import sys
from dotenv import load_dotenv

# .env 파일 로드 (인코딩 명시)
# Windows 환경에서 인코딩 문제 방지를 위해 UTF-8 명시
try:
    load_dotenv(encoding='utf-8')
except TypeError:
    # 구버전 python-dotenv는 encoding 파라미터를 지원하지 않을 수 있음
    load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-#j^r@s*tdgq55i(a%plyhwgr5m*dhjs%#2m^6gvp3s=kbt57$%')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'corsheaders',  # CORS 헤더 앱 추가
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',  # 필터링 지원
    'drf_spectacular',  # API 문서화 (Swagger/OpenAPI)
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'authentication',
    'products',  # 제품 관리 앱
    'sellers',  # 판매자 관리 앱
    'orders',  # 주문 관리 앱
    'data_pipeline',  # 데이터 파이프라인 (CSV/JSON → DB)
    'analytics',  # Admin 분석/집계 앱
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS 미들웨어 추가
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # allauth 미들웨어 추가
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project_self.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project_self.wsgi.application'

# 정적 파일 설정
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = 'static/'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DB_ENGINE = os.getenv('DB_ENGINE', 'django.db.backends.sqlite3')
DB_NAME = os.getenv('DB_NAME', str(BASE_DIR / 'db.sqlite3'))
DB_USER = os.getenv('DB_USER', '')
DB_PASSWORD = os.getenv('DB_PASSWORD', '')
DB_HOST = os.getenv('DB_HOST', '')
DB_PORT = os.getenv('DB_PORT', '')
ML_API_URL = os.getenv('ML_API_URL', 'http://localhost:8001')
REDIS_URL = os.getenv('REDIS_URL', 'redis://redis:6379/0')
# 상품 목록 캐시 TTL (초 단위) - 환경변수 PRODUCT_LIST_CACHE_TTL 로 조정 가능
PRODUCT_LIST_CACHE_TTL = int(os.getenv('PRODUCT_LIST_CACHE_TTL', '60'))

# 환경변수 값에 따라 SQLite(기본) 또는 Postgres 등으로 분기
if DB_ENGINE == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': DB_NAME,
            'OPTIONS': {
                'timeout': 20,
            },
        }
    }
elif DB_ENGINE == 'django.db.backends.postgresql' or DB_ENGINE == 'django.db.backends.postgresql_psycopg2':
    # PostgreSQL: charset 옵션 없음 (데이터베이스 레벨에서 인코딩 설정)
    # client_encoding을 UTF-8로 명시적으로 설정하여 인코딩 문제 방지
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
            'OPTIONS': {
                'client_encoding': 'UTF8',
            },
        }
    }
else:
    # MySQL/MariaDB: charset 옵션 사용 가능
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
            'OPTIONS': {
                'charset': 'utf8mb4',
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }

# Cache (Redis)
# 기본: RedisCache. 테스트 실행 시(CI 포함) 로컬 메모리 캐시로 전환해 외부 의존성 없이 검증.
_cache_backend = os.getenv('DJANGO_CACHE_BACKEND', 'redis')
_is_test_env = 'test' in sys.argv
if _is_test_env:
    _cache_backend = os.getenv('DJANGO_TEST_CACHE_BACKEND', 'locmem')

if _cache_backend == 'locmem':
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-locmem',
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Frontend origin (admin analytics 등 SPA 링크용)
FRONTEND_ORIGIN = os.getenv('FRONTEND_ORIGIN', 'http://localhost:8080')

# ========================= Authentication 모듈 설정 =========================
# 커스텀 User 모델 사용
AUTH_USER_MODEL = 'authentication.User'
SITE_ID = 1

# REST Framework 설정
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.AllowAny',),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# API 문서화 설정 (drf-spectacular)
SPECTACULAR_SETTINGS = {
    'TITLE': 'SSAFY 18기 4팀 - 식료품 쇼핑몰 API',
    'DESCRIPTION': '''
## 프로젝트 개요
SSAFY Class 18 Team 4 Final Capstone Project - 식료품 쇼핑몰 백엔드 API

## 인증 방식
- JWT (JSON Web Token) 기반 인증
- Authorization 헤더에 `Bearer <access_token>` 형식으로 전송

## 주요 기능
- **인증**: 회원가입, 로그인, OAuth (Google, Kakao)
- **상품**: 상품 목록/상세, 신상품, 베스트 상품
- **장바구니**: 장바구니 관리
- **찜 목록**: 위시리스트 관리
- **주문**: 주문 생성/조회
- **리뷰**: 상품 리뷰 작성/조회
- **판매자**: 판매자 상품 관리
- **추천**: 개인화 추천 시스템
''',
    'VERSION': '2.1.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/api/',
    'TAGS': [
        {'name': '인증', 'description': '회원가입, 로그인, 토큰 관리'},
        {'name': '상품', 'description': '상품 목록, 상세, 검색, 필터링'},
        {'name': '신상품', 'description': '신상품 목록 (최신 40개)'},
        {'name': '베스트 상품', 'description': '베스트 상품 목록 (판매량 기준 40개)'},
        {'name': '장바구니', 'description': '장바구니 CRUD'},
        {'name': '찜 목록', 'description': '위시리스트 관리'},
        {'name': '주문', 'description': '주문 생성 및 조회'},
        {'name': '리뷰', 'description': '상품 리뷰 CRUD'},
        {'name': '판매자', 'description': '판매자 상품 관리, 이미지 S3 업로드'},
        {'name': '추천', 'description': '개인화 추천 API'},
        {'name': '카테고리', 'description': '카테고리 조회'},
    ],
}

# SimpleJWT 설정
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_ACCESS_TOKEN_LIFETIME', 15))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_TOKEN_LIFETIME', 7))),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# 인증 백엔드 설정
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'authentication.backends.EmailAuthBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

# CORS 설정 (프론트엔드와 통신을 위해)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Vite 기본 포트 (로컬 개발)
    "http://localhost:3000",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:3000",
    "http://localhost:8080",  # Docker Frontend 포트
    "http://127.0.0.1:8080",
]

# 환경변수로 추가 CORS 출처 설정 가능
_extra_cors = os.getenv('CORS_ALLOWED_ORIGINS', '')
if _extra_cors:
    CORS_ALLOWED_ORIGINS.extend([o.strip() for o in _extra_cors.split(',') if o.strip()])

CORS_ALLOW_CREDENTIALS = True

# CSRF 신뢰 출처 설정 (CORS와 동일하게)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3000",
    "http://localhost:8080",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8080",
]

# 환경변수로 추가 CSRF 출처 설정 가능
_extra_csrf = os.getenv('CSRF_TRUSTED_ORIGINS', '')
if _extra_csrf:
    CSRF_TRUSTED_ORIGINS.extend([o.strip() for o in _extra_csrf.split(',') if o.strip()])

# 이메일 설정
# 개발 환경에서는 console 백엔드를 사용하여 즉시 응답 (타임아웃 방지)
# 프로덕션 환경에서는 SMTP 백엔드 사용
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
# 개발 환경에서는 기본값 사용 (console 백엔드 사용 시 필요 없지만 설정 오류 방지)
DEFAULT_FROM_EMAIL = os.getenv('EMAIL_VERIFICATION_FROM_EMAIL', 'noreply@example.com')

# SMTP 타임아웃 설정 (초 단위)
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', 5))

# ========================= AWS S3 설정 =========================
# 판매자 상품 이미지 업로드용 S3 설정
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY', '')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_S3_BUCKET', 'self-json-backup')
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION', 'ap-northeast-2')
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'

# S3 업로드 경로 설정
# Base: s3://self-json-backup/seller_profile/
# 상품 이미지
AWS_S3_THUMBNAIL_PREFIX = os.getenv('AWS_S3_THUMBNAIL_PREFIX', 'seller_profile/seller_product_thumbnail/')
AWS_S3_PRODUCT_DETAIL_PREFIX = os.getenv('AWS_S3_PRODUCT_DETAIL_PREFIX', 'seller_profile/seller_product_detail/')

# 판매자 프로필/브랜드 이미지
AWS_S3_SELLER_PROFILE_PREFIX = os.getenv('AWS_S3_SELLER_PROFILE_PREFIX', 'seller_profile/seller_profile/')
AWS_S3_BRAND_LOGO_PREFIX = os.getenv('AWS_S3_BRAND_LOGO_PREFIX', 'seller_profile/brand_logo/')
AWS_S3_BRAND_BANNER_PREFIX = os.getenv('AWS_S3_BRAND_BANNER_PREFIX', 'seller_profile/brand_banner/')

# S3 파일 설정
AWS_S3_FILE_OVERWRITE = False  # 동일 파일명 덮어쓰기 방지
AWS_DEFAULT_ACL = 'public-read'  # 공개 읽기 권한
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',  # 24시간 캐시
}

# ========================= GMS (SSAFY GPT Proxy) 설정 =========================
# 상품명에서 재료 추출을 위한 LLM API 설정
GMS_API_BASE_URL = os.getenv('GMS_API_BASE_URL', 'https://gms.ssafy.io/gmsapi/api.openai.com/v1')
GMS_API_KEY = os.getenv('GMS_API_KEY', '')
GMS_MODEL = os.getenv('GMS_MODEL', 'gpt-4o-mini')
GMS_MAX_RETRIES = int(os.getenv('GMS_MAX_RETRIES', 3))
GMS_TIMEOUT = int(os.getenv('GMS_TIMEOUT', 30))

# ========================= Celery 설정 =========================
# Redis를 브로커와 결과 백엔드로 사용
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL

# 직렬화 설정
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# 시간대 설정
CELERY_TIMEZONE = 'Asia/Seoul'
CELERY_ENABLE_UTC = True

# 태스크 설정
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30분 (GMS API 배치 처리 고려)
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25분 (soft limit)

# Worker 설정
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # 순차 처리 (Rate Limit 대응)
CELERY_WORKER_CONCURRENCY = int(os.getenv('CELERY_CONCURRENCY', 4))

# 재시도 설정
CELERY_TASK_ACKS_LATE = True  # 태스크 완료 후 ACK (장애 복구)
CELERY_TASK_REJECT_ON_WORKER_LOST = True

# 결과 만료 시간 (24시간)
CELERY_RESULT_EXPIRES = 60 * 60 * 24

# GMS 추출 관련 설정
GMS_EXTRACTION_BATCH_SIZE = int(os.getenv('GMS_EXTRACTION_BATCH_SIZE', 100))
GMS_EXTRACTION_MIN_CONFIDENCE = float(os.getenv('GMS_EXTRACTION_MIN_CONFIDENCE', 0.7))
GMS_EXTRACTION_USE_FALLBACK = os.getenv('GMS_EXTRACTION_USE_FALLBACK', 'True').lower() == 'true'
