# Generated by Django 5.2.4 on 2025-12-14 20:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0002_add_delivery_memo_to_useraddress"),
        ("products", "0007_add_detail_full_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PredInstacartDepartment",
            fields=[
                ("id", models.SmallIntegerField(primary_key=True, serialize=False, verbose_name="Instacart 부서 ID")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="부서명")),
                ("description", models.CharField(blank=True, default="", max_length=255, verbose_name="설명")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
            ],
            options={
                "verbose_name": "Instacart 부서",
                "verbose_name_plural": "Instacart 부서들",
                "db_table": "pred_instacart_departments",
            },
        ),
        migrations.CreateModel(
            name="PredProductEmbedding",
            fields=[
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="embedding",
                        serialize=False,
                        to="products.product",
                        verbose_name="상품",
                    ),
                ),
                (
                    "bert_vector",
                    models.JSONField(
                        blank=True, help_text="768차원 float 배열", null=True, verbose_name="BERT 임베딩 벡터"
                    ),
                ),
                (
                    "bert_version",
                    models.CharField(blank=True, default="", max_length=50, verbose_name="BERT 모델 버전"),
                ),
                ("bert_updated_at", models.DateTimeField(blank=True, null=True, verbose_name="BERT 임베딩 갱신 일시")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
            ],
            options={
                "verbose_name": "상품 임베딩",
                "verbose_name_plural": "상품 임베딩들",
                "db_table": "pred_product_embeddings",
            },
        ),
        migrations.CreateModel(
            name="PredIngredient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="재료명")),
                (
                    "name_normalized",
                    models.CharField(help_text="검색용 정규화 이름", max_length=100, verbose_name="정규화된 재료명"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("채소", "채소"),
                            ("육류", "육류"),
                            ("수산물", "수산물"),
                            ("양념", "양념"),
                            ("유제품", "유제품"),
                            ("곡류", "곡류"),
                            ("기타", "기타"),
                        ],
                        default="",
                        max_length=50,
                        verbose_name="재료 분류",
                    ),
                ),
                ("substitute_group_id", models.IntegerField(blank=True, null=True, verbose_name="대체재 그룹 ID")),
                (
                    "importance_score",
                    models.DecimalField(decimal_places=2, default=0.5, max_digits=3, verbose_name="중요도 점수"),
                ),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False, help_text="고추장, 된장 등 가공식품", verbose_name="가공식품 여부"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
            ],
            options={
                "verbose_name": "재료",
                "verbose_name_plural": "재료들",
                "db_table": "pred_ingredients",
                "indexes": [
                    models.Index(fields=["name_normalized"], name="ix_ingredients_name"),
                    models.Index(fields=["category"], name="ix_ingredients_category"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PredInstacartAisle",
            fields=[
                ("id", models.SmallIntegerField(primary_key=True, serialize=False, verbose_name="Instacart 통로 ID")),
                ("name", models.CharField(max_length=100, verbose_name="통로명")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aisles",
                        to="pred.predinstacartdepartment",
                        verbose_name="소속 부서",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instacart 통로",
                "verbose_name_plural": "Instacart 통로들",
                "db_table": "pred_instacart_aisles",
            },
        ),
        migrations.CreateModel(
            name="PredInstacartOrder",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False, verbose_name="Instacart 주문 ID")),
                (
                    "user_id",
                    models.IntegerField(
                        help_text="SelF users 테이블과 무관한 Instacart 내부 ID", verbose_name="Instacart 사용자 ID"
                    ),
                ),
                (
                    "order_number",
                    models.SmallIntegerField(help_text="해당 사용자의 N번째 주문", verbose_name="주문 순서"),
                ),
                (
                    "order_dow",
                    models.SmallIntegerField(
                        help_text="0=일요일, 6=토요일",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                        verbose_name="주문 요일",
                    ),
                ),
                (
                    "order_hour_of_day",
                    models.SmallIntegerField(
                        help_text="0-23",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                        verbose_name="주문 시간",
                    ),
                ),
                (
                    "days_since_prior_order",
                    models.SmallIntegerField(blank=True, null=True, verbose_name="이전 주문 후 경과일"),
                ),
                (
                    "eval_set",
                    models.CharField(
                        choices=[("prior", "이전 주문"), ("train", "학습용"), ("test", "테스트용")],
                        max_length=10,
                        verbose_name="데이터셋 타입",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
            ],
            options={
                "verbose_name": "Instacart 주문",
                "verbose_name_plural": "Instacart 주문들",
                "db_table": "pred_instacart_orders",
                "indexes": [
                    models.Index(fields=["user_id"], name="ix_inst_orders_user"),
                    models.Index(fields=["eval_set"], name="ix_inst_orders_eval"),
                    models.Index(fields=["eval_set", "order_dow", "order_hour_of_day"], name="ix_inst_orders_time"),
                    models.Index(fields=["user_id", "order_number"], name="ix_inst_orders_user_seq"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PredInstacartProduct",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False, verbose_name="Instacart 상품 ID")),
                ("name", models.CharField(max_length=300, verbose_name="상품명")),
                (
                    "name_normalized",
                    models.CharField(
                        help_text="소문자 변환, 특수문자 제거된 상품명", max_length=300, verbose_name="정규화된 상품명"
                    ),
                ),
                ("order_count", models.IntegerField(default=0, verbose_name="총 주문 횟수")),
                ("reorder_count", models.IntegerField(default=0, verbose_name="재주문 횟수")),
                (
                    "reorder_rate",
                    models.DecimalField(
                        decimal_places=4, default=0, help_text="0.0000~1.0000", max_digits=5, verbose_name="재주문율"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "aisle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="pred.predinstacartaisle",
                        verbose_name="소속 통로",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instacart 상품",
                "verbose_name_plural": "Instacart 상품들",
                "db_table": "pred_instacart_products",
            },
        ),
        migrations.CreateModel(
            name="PredInstacartOrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "add_to_cart_order",
                    models.SmallIntegerField(help_text="1부터 시작", verbose_name="장바구니 추가 순서"),
                ),
                ("is_reordered", models.BooleanField(default=False, verbose_name="재주문 여부")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pred.predinstacartorder",
                        verbose_name="주문",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="pred.predinstacartproduct",
                        verbose_name="상품",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instacart 주문 상품",
                "verbose_name_plural": "Instacart 주문 상품들",
                "db_table": "pred_instacart_order_items",
            },
        ),
        migrations.CreateModel(
            name="PredInstacartTimePattern",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "time_slot",
                    models.CharField(
                        choices=[
                            ("morning", "아침 (6-10시)"),
                            ("lunch", "점심 (11-14시)"),
                            ("dinner", "저녁 (17-21시)"),
                            ("night", "야간 (기타)"),
                        ],
                        max_length=20,
                        verbose_name="시간대",
                    ),
                ),
                (
                    "day_type",
                    models.CharField(
                        choices=[("weekday", "평일"), ("weekend", "주말")], max_length=20, verbose_name="요일 타입"
                    ),
                ),
                (
                    "popularity_score",
                    models.BigIntegerField(help_text="해당 시간대/요일의 총 주문 횟수", verbose_name="인기도 점수"),
                ),
                ("reorder_rate", models.DecimalField(decimal_places=4, max_digits=5, verbose_name="평균 재주문율")),
                ("aggregated_at", models.DateTimeField(auto_now=True, verbose_name="집계 일시")),
                (
                    "instacart_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_patterns",
                        to="pred.predinstacartdepartment",
                        verbose_name="Instacart 부서",
                    ),
                ),
                (
                    "self_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instacart_time_patterns",
                        to="products.category",
                        verbose_name="매핑된 SelF 카테고리",
                    ),
                ),
            ],
            options={
                "verbose_name": "시간대별 인기 패턴",
                "verbose_name_plural": "시간대별 인기 패턴들",
                "db_table": "pred_instacart_time_patterns",
            },
        ),
        migrations.CreateModel(
            name="PredItemSimilarity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "similarity_score",
                    models.DecimalField(
                        decimal_places=4, help_text="0.0000~1.0000", max_digits=5, verbose_name="유사도 점수"
                    ),
                ),
                (
                    "similarity_type",
                    models.CharField(
                        choices=[
                            ("embedding", "임베딩 코사인"),
                            ("copurchase", "동시 구매"),
                            ("category", "카테고리 기반"),
                        ],
                        max_length=20,
                        verbose_name="유사도 타입",
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True, verbose_name="계산 일시")),
                (
                    "source_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similar_items_as_source",
                        to="products.product",
                        verbose_name="기준 상품",
                    ),
                ),
                (
                    "target_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similar_items_as_target",
                        to="products.product",
                        verbose_name="유사 상품",
                    ),
                ),
            ],
            options={
                "verbose_name": "상품 유사도",
                "verbose_name_plural": "상품 유사도들",
                "db_table": "pred_item_similarity",
            },
        ),
        migrations.CreateModel(
            name="PredPriceAnomalyCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("current_price", models.IntegerField(verbose_name="현재 가격")),
                ("previous_price", models.IntegerField(blank=True, null=True, verbose_name="이전 가격")),
                (
                    "price_change_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True, verbose_name="가격 변동률 (%)"
                    ),
                ),
                (
                    "anomaly_score",
                    models.DecimalField(
                        decimal_places=4, help_text="0.0000~1.0000", max_digits=5, verbose_name="이상치 점수"
                    ),
                ),
                (
                    "detection_methods",
                    models.CharField(help_text="zscore,iqr,ma (쉼표 구분)", max_length=100, verbose_name="탐지 방법들"),
                ),
                (
                    "zscore_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True, verbose_name="Z-Score 값"
                    ),
                ),
                ("iqr_lower_bound", models.IntegerField(blank=True, null=True, verbose_name="IQR 하한")),
                ("ma_7day", models.IntegerField(blank=True, null=True, verbose_name="7일 이동평균")),
                ("analyzed_at", models.DateTimeField(auto_now=True, verbose_name="분석 일시")),
                ("expires_at", models.DateTimeField(verbose_name="만료 일시")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anomaly_caches",
                        to="products.category",
                        verbose_name="카테고리",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomaly_cache",
                        to="products.product",
                        verbose_name="상품",
                    ),
                ),
            ],
            options={
                "verbose_name": "가격 이상치 캐시",
                "verbose_name_plural": "가격 이상치 캐시들",
                "db_table": "pred_price_anomaly_cache",
            },
        ),
        migrations.CreateModel(
            name="PredProductMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "similarity_score",
                    models.DecimalField(
                        decimal_places=4, help_text="0.0000~1.0000", max_digits=5, verbose_name="유사도 점수"
                    ),
                ),
                (
                    "mapping_method",
                    models.CharField(
                        choices=[("category", "카테고리 기반"), ("text", "텍스트 유사도"), ("manual", "수동 매핑")],
                        max_length=50,
                        verbose_name="매핑 방법",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화 여부")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "instacart_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="self_mappings",
                        to="pred.predinstacartproduct",
                        verbose_name="Instacart 상품",
                    ),
                ),
                (
                    "self_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instacart_mappings",
                        to="products.product",
                        verbose_name="SelF 상품",
                    ),
                ),
            ],
            options={
                "verbose_name": "상품 매핑",
                "verbose_name_plural": "상품 매핑들",
                "db_table": "pred_product_mapping",
            },
        ),
        migrations.CreateModel(
            name="PredRecipe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_site", models.CharField(default="10000recipe", max_length=50, verbose_name="출처 사이트")),
                (
                    "source_id",
                    models.CharField(help_text="원본 사이트의 레시피 ID", max_length=50, verbose_name="원본 ID"),
                ),
                ("source_url", models.TextField(blank=True, default="", verbose_name="원본 URL")),
                ("name", models.CharField(max_length=200, verbose_name="레시피명")),
                (
                    "name_normalized",
                    models.CharField(help_text="검색용 정규화 이름", max_length=200, verbose_name="정규화된 레시피명"),
                ),
                ("description", models.TextField(blank=True, default="", verbose_name="설명")),
                ("thumbnail_url", models.TextField(blank=True, default="", verbose_name="썸네일 URL")),
                ("cooking_time_min", models.SmallIntegerField(blank=True, null=True, verbose_name="조리 시간 (분)")),
                ("servings", models.SmallIntegerField(blank=True, null=True, verbose_name="인분")),
                (
                    "difficulty",
                    models.CharField(
                        blank=True,
                        choices=[("easy", "쉬움"), ("medium", "보통"), ("hard", "어려움")],
                        default="",
                        max_length=20,
                        verbose_name="난이도",
                    ),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="조회수")),
                ("like_count", models.IntegerField(default=0, verbose_name="좋아요 수")),
                ("rating", models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name="평점")),
                ("rating_count", models.IntegerField(default=0, verbose_name="평점 수")),
                (
                    "category_main",
                    models.CharField(
                        blank=True, default="", help_text="한식, 양식, 중식 등", max_length=50, verbose_name="대분류"
                    ),
                ),
                (
                    "category_sub",
                    models.CharField(
                        blank=True, default="", help_text="찌개, 볶음, 구이 등", max_length=50, verbose_name="소분류"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화 여부")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
            ],
            options={
                "verbose_name": "레시피",
                "verbose_name_plural": "레시피들",
                "db_table": "pred_recipes",
                "indexes": [
                    models.Index(fields=["name_normalized"], name="ix_recipes_name"),
                    models.Index(fields=["category_main", "category_sub"], name="ix_recipes_category"),
                    models.Index(fields=["-rating", "-like_count"], name="ix_recipes_popularity"),
                ],
                "unique_together": {("source_site", "source_id")},
            },
        ),
        migrations.CreateModel(
            name="PredRecipeIngredient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "quantity_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='"1/2컵", "약간", "2개" 등',
                        max_length=100,
                        verbose_name="분량 텍스트",
                    ),
                ),
                (
                    "quantity_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="파싱된 수량"
                    ),
                ),
                ("quantity_unit", models.CharField(blank=True, default="", max_length=20, verbose_name="파싱된 단위")),
                ("is_required", models.BooleanField(default=True, verbose_name="필수 재료 여부")),
                ("is_main", models.BooleanField(default=False, verbose_name="주재료 여부")),
                ("display_order", models.SmallIntegerField(default=0, verbose_name="표시 순서")),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to="pred.predingredient",
                        verbose_name="재료",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="pred.predrecipe",
                        verbose_name="레시피",
                    ),
                ),
            ],
            options={
                "verbose_name": "레시피 재료",
                "verbose_name_plural": "레시피 재료들",
                "db_table": "pred_recipe_ingredients",
            },
        ),
        migrations.CreateModel(
            name="PredRecommendationCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("home", "메인 홈"),
                            ("category", "카테고리"),
                            ("product_detail", "상품 상세"),
                            ("cart", "장바구니"),
                            ("search", "검색 결과"),
                            ("timedeal", "타임딜"),
                        ],
                        max_length=30,
                        verbose_name="페이지 타입",
                    ),
                ),
                (
                    "context_hash",
                    models.CharField(
                        help_text="SHA256(category_id + product_id + cart_items + time_slot)",
                        max_length=64,
                        verbose_name="컨텍스트 해시",
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(help_text="[{product_id, score, reason}, ...]", verbose_name="추천 결과"),
                ),
                ("model_used", models.CharField(max_length=100, verbose_name="사용된 모델들")),
                ("expires_at", models.DateTimeField(verbose_name="만료 일시")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL이면 비로그인 사용자",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_caches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "추천 캐시",
                "verbose_name_plural": "추천 캐시들",
                "db_table": "pred_recommendation_cache",
            },
        ),
        migrations.CreateModel(
            name="PredUserEmbedding",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="recommendation_embedding",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
                (
                    "preference_vector",
                    models.JSONField(blank=True, help_text="768차원 float 배열", null=True, verbose_name="선호도 벡터"),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("cold", "콜드 유저 (데이터 부족)"),
                            ("lukewarm", "루크웜 유저 (제한적 개인화)"),
                            ("warm", "웜 유저 (완전 개인화)"),
                        ],
                        default="cold",
                        max_length=20,
                        verbose_name="사용자 타입",
                    ),
                ),
                ("interaction_count", models.IntegerField(default=0, verbose_name="총 상호작용 수")),
                (
                    "last_interaction_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="마지막 상호작용 일시"),
                ),
                ("version", models.CharField(blank=True, default="", max_length=20, verbose_name="임베딩 버전")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
            ],
            options={
                "verbose_name": "사용자 임베딩",
                "verbose_name_plural": "사용자 임베딩들",
                "db_table": "pred_user_embeddings",
                "indexes": [
                    models.Index(fields=["user_type"], name="ix_user_emb_type"),
                    models.Index(fields=["updated_at"], name="ix_user_emb_updated"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PredIngredientProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("similarity_score", models.DecimalField(decimal_places=4, max_digits=5, verbose_name="유사도 점수")),
                (
                    "mapping_method",
                    models.CharField(
                        choices=[("exact", "정확 매칭"), ("partial", "부분 매칭"), ("category", "카테고리 매칭")],
                        max_length=50,
                        verbose_name="매핑 방법",
                    ),
                ),
                ("priority", models.SmallIntegerField(default=0, verbose_name="우선순위")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화 여부")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="pred.predingredient",
                        verbose_name="재료",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_mappings",
                        to="products.product",
                        verbose_name="상품",
                    ),
                ),
            ],
            options={
                "verbose_name": "재료-상품 매핑",
                "verbose_name_plural": "재료-상품 매핑들",
                "db_table": "pred_ingredient_products",
                "indexes": [
                    models.Index(fields=["ingredient"], name="ix_ing_prod_ingredient"),
                    models.Index(fields=["product"], name="ix_ing_prod_product"),
                ],
                "unique_together": {("ingredient", "product")},
            },
        ),
        migrations.CreateModel(
            name="PredInstacartCategoryMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2, default=1.0, help_text="0.00~1.00", max_digits=3, verbose_name="신뢰도"
                    ),
                ),
                ("mapping_note", models.CharField(blank=True, default="", max_length=200, verbose_name="매핑 메모")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화 여부")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "instacart_aisle",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL이면 부서 전체 매핑",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_mappings",
                        to="pred.predinstacartaisle",
                        verbose_name="Instacart 통로",
                    ),
                ),
                (
                    "self_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instacart_mappings",
                        to="products.category",
                        verbose_name="SelF 카테고리",
                    ),
                ),
                (
                    "instacart_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_mappings",
                        to="pred.predinstacartdepartment",
                        verbose_name="Instacart 부서",
                    ),
                ),
            ],
            options={
                "verbose_name": "카테고리 매핑",
                "verbose_name_plural": "카테고리 매핑들",
                "db_table": "pred_instacart_category_mapping",
                "indexes": [
                    models.Index(fields=["instacart_department"], name="ix_cat_mapping_dept"),
                    models.Index(fields=["self_category"], name="ix_cat_mapping_self"),
                ],
                "unique_together": {("instacart_department", "instacart_aisle", "self_category")},
            },
        ),
        migrations.AddIndex(
            model_name="predinstacartaisle",
            index=models.Index(fields=["department"], name="ix_inst_aisles_dept"),
        ),
        migrations.AlterUniqueTogether(
            name="predinstacartaisle",
            unique_together={("department", "name")},
        ),
        migrations.AddIndex(
            model_name="predinstacartproduct",
            index=models.Index(fields=["aisle"], name="ix_inst_products_aisle"),
        ),
        migrations.AddIndex(
            model_name="predinstacartproduct",
            index=models.Index(fields=["name_normalized"], name="ix_inst_products_name"),
        ),
        migrations.AddIndex(
            model_name="predinstacartproduct",
            index=models.Index(fields=["-order_count"], name="ix_inst_products_pop"),
        ),
        migrations.AddIndex(
            model_name="predinstacartorderitem",
            index=models.Index(fields=["order"], name="ix_inst_oi_order"),
        ),
        migrations.AddIndex(
            model_name="predinstacartorderitem",
            index=models.Index(fields=["product"], name="ix_inst_oi_product"),
        ),
        migrations.AddIndex(
            model_name="predinstacartorderitem",
            index=models.Index(fields=["product", "is_reordered"], name="ix_inst_oi_prod_reord"),
        ),
        migrations.AlterUniqueTogether(
            name="predinstacartorderitem",
            unique_together={("order", "product")},
        ),
        migrations.AddIndex(
            model_name="predinstacarttimepattern",
            index=models.Index(fields=["time_slot", "day_type", "-popularity_score"], name="ix_time_patterns_lookup"),
        ),
        migrations.AddIndex(
            model_name="predinstacarttimepattern",
            index=models.Index(fields=["self_category"], name="ix_time_patterns_self_cat"),
        ),
        migrations.AlterUniqueTogether(
            name="predinstacarttimepattern",
            unique_together={("time_slot", "day_type", "instacart_department")},
        ),
        migrations.AddIndex(
            model_name="preditemsimilarity",
            index=models.Index(fields=["source_product", "-similarity_score"], name="ix_item_sim_source"),
        ),
        migrations.AddIndex(
            model_name="preditemsimilarity",
            index=models.Index(fields=["target_product"], name="ix_item_sim_target"),
        ),
        migrations.AddIndex(
            model_name="preditemsimilarity",
            index=models.Index(
                fields=["source_product", "similarity_type", "-similarity_score"], name="ix_item_sim_src_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="preditemsimilarity",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_product", models.F("target_product")), _negated=True),
                name="check_different_products",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="preditemsimilarity",
            unique_together={("source_product", "target_product", "similarity_type")},
        ),
        migrations.AddIndex(
            model_name="predpriceanomalycache",
            index=models.Index(fields=["-anomaly_score"], name="ix_anomaly_score"),
        ),
        migrations.AddIndex(
            model_name="predpriceanomalycache",
            index=models.Index(fields=["category"], name="ix_anomaly_category"),
        ),
        migrations.AddIndex(
            model_name="predpriceanomalycache",
            index=models.Index(fields=["expires_at"], name="ix_anomaly_expires"),
        ),
        migrations.AddIndex(
            model_name="predproductmapping",
            index=models.Index(fields=["self_product"], name="ix_prod_mapping_self"),
        ),
        migrations.AddIndex(
            model_name="predproductmapping",
            index=models.Index(fields=["instacart_product"], name="ix_prod_mapping_inst"),
        ),
        migrations.AddIndex(
            model_name="predproductmapping",
            index=models.Index(fields=["-similarity_score"], name="ix_prod_mapping_score"),
        ),
        migrations.AlterUniqueTogether(
            name="predproductmapping",
            unique_together={("self_product", "instacart_product")},
        ),
        migrations.AddIndex(
            model_name="predrecipeingredient",
            index=models.Index(fields=["recipe"], name="ix_recipe_ing_recipe"),
        ),
        migrations.AddIndex(
            model_name="predrecipeingredient",
            index=models.Index(fields=["ingredient", "recipe"], name="ix_recipe_ing_ingred"),
        ),
        migrations.AddIndex(
            model_name="predrecipeingredient",
            index=models.Index(fields=["recipe", "-is_main", "-is_required"], name="ix_recipe_ing_main"),
        ),
        migrations.AlterUniqueTogether(
            name="predrecipeingredient",
            unique_together={("recipe", "ingredient")},
        ),
        migrations.AddIndex(
            model_name="predrecommendationcache",
            index=models.Index(fields=["user"], name="ix_rec_cache_user"),
        ),
        migrations.AddIndex(
            model_name="predrecommendationcache",
            index=models.Index(fields=["user", "page_type", "context_hash", "expires_at"], name="ix_rec_cache_lookup"),
        ),
        migrations.AddIndex(
            model_name="predrecommendationcache",
            index=models.Index(fields=["expires_at"], name="ix_rec_cache_expires"),
        ),
        migrations.AlterUniqueTogether(
            name="predrecommendationcache",
            unique_together={("user", "page_type", "context_hash")},
        ),
    ]
